name: pullrequestopen
on:
 pull_request:
  types: 
   - opened
  branches:
   - master
jobs:
 echo-triggers:
  runs-on: windows-latest
  steps:
   - name: windows platform
     shell: bash
     run: echo "windwos platform"
